### ISSUE TITLE
Options to disable (accidential) hotbar sorting.

### ISSUE THREAD

**Issue by mk-pmb** [TerminalMC/ClientSort#10]
### Request Description

When I switch between survival and creative mode, too often I accidentially middle-click a hotbar item to draw a stack of that, but forgot I'm still in survival so instead it sorts my hotbar. Thus I'd like to have an option to disable sorting the hotbar.

### Minecraft Version

1.21

**Comment by NotRyken** [comment]
This is already a thing though; `Hotbar Mode` - `Off`

**Comment by mk-pmb** [comment]
Thanks! No idea why I missed that option when I configured it the first time.
