### ISSUE TITLE
Option to restrict chest/inventory slots that accept the sort click

### ISSUE THREAD

**Issue by mk-pmb** [TerminalMC/ClientSort#11]
### Request Description

For multi-line inventories (player inventory, chest etc.) I'd like an option to restrict which slots can accept the sort command. Similar to the hotbar option I just requested, this is meant to avoid accidential sorting when switching between survival and creative and forgetting which one you're in.

The option could be named "Which slot can you click to sort a multi-line inventory?" and choices should be any (default), top-left, top-right, bottom-left, bottom-right, none.

### Minecraft Version

1.21

**Comment by NotRyken** [comment]
Why not just use a keybind that doesn't have a creative-mode function?

**Comment by mk-pmb** [comment]
That's actually a good idea. I was too caught in habit. Thanks!
