### ISSUE TITLE
Sorting with bundles breaks sorting and just fills bundles 

### ISSUE THREAD

**Issue by gatolocoses** [TerminalMC/ClientSort#13]
### Mod Version

v21.2.0-beta.01-Fabric-1.21.2

### Mod Loader

fabric

### Minecraft Version

1.21.2

### Bug Description

Before sorting 
![Before sorting](https://github.com/user-attachments/assets/5f378101-5f8a-4ef7-86a2-812841947aae)
After sorting
![image](https://github.com/user-attachments/assets/ba4f8577-2b4e-4174-838d-da45068629e4)

### Expected Behavior

avoid trying to sort a bundle into an inventory space that already has an item on it 

### Reproduction Steps

just have bundles and items in an inventory or chest and try to sort 

### Log File

not needed

**Comment by NotRyken** [comment]
Right yeah sorry I completely overlooked that. Will have to add some form of exception since the sorting implementation requires swap-pickup which obviously breaks with bundles.

**Comment by NotRyken** [comment]
Fix has been released as `21.2.0-beta.02`. Thanks for reporting, please let me know if you notice any other issues.
