### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by thehamish555** [TerminalMC/ClientSort#16]
### Mod Version

1.1.0+1.21.x

### Mod Loader

Fabric/NeoForge

### Minecraft Version

1.21.x

### Bug Description

![image](https://github.com/user-attachments/assets/8f39db53-3a0b-4c3e-81dd-a0a4c599b46e)
The game version tag on the modrinth page does not match the downloaded version (causing issues with automatic mod downloaders such as ferium)

### Expected Behavior

game versions should match

### Reproduction Steps

go here
https://modrinth.com/mod/clientsort/versions

download latest one tagged as 1.21-1.21.1 and crashes since its 1.21.3 not 1.21.1

### Log File

i dont think this is needed-

**Comment by NotRyken** [comment]
Hey, thanks so much for reporting this. I was running updates on several mods and I guess it just slipped through. Fixed now.
