### ISSUE TITLE
A way to disable sorting the offhand with the hotbar

### ISSUE THREAD

**Issue by Magnogen** [TerminalMC/ClientSort#19]
### Before you open a new issue;

- [x] **Are you requesting either a new feature or an improvement of existing  functionality?** If you want to request an update or backport, please use Discord.
- [X] **Have you checked whether a similar request already exists (either open or closed)?**  If your idea has been requested previously, please comment there instead.
- [X] **Have you checked whether the feature already exists on the latest version?** If you want to request that an existing feature be backported, please use Discord.

### Request Description

at the moment, sorting the hotbar in your inventory includes the hotbar in with what needs to be sorted. sorting the hotbar in any other inventory (like a chest) where the offhand isnt accessible sorts as expected, treating the offhand as its separate slot group. see video.

https://github.com/user-attachments/assets/60321eac-6ebf-4515-a97d-e411df253c4f

**Comment by NotRyken** [comment]
@Magnogen Config -> General -> Extra Slot Mode : None
