### ISSUE TITLE
[1.21] NeoForge, servers cannot start with ClientSort installed

### ISSUE THREAD

**Issue by NielsPilgaard** [TerminalMC/ClientSort#3]
### Mod Version

ClientSort-NeoForge-1.21-0.4.0

### Mod Loader

NeoForge

### Minecraft Version

1.21.0

### Bug Description

When ClientSort is in the mods folder of a server, it cannot start.

### Reproduction Steps

Make a NeoForge server
Add ClientSort
Start it

### Crash Report (optional)

https://gist.github.com/NielsPilgaard/a526f5386c616ce7bca148427d8f9e1c

**Comment by NotRyken** [comment]
Are you surprised that a mod, marked as client-side in no less than 4 places including its name, doesn't work on a server?

**Comment by NielsPilgaard** [comment]
I am not, but it's common practice for client-side mods to do nothing when loaded on a server, to prevent crashes when people forget to remove them.

I just wanted to let you know.

**Comment by NotRyken** [comment]
I appreciate that, and have 'fixed' it in f1201ff, for release in v0.5.0 depending on how the fix for #4 goes.

Perhaps I should add an 'expected behavior' section to the bug report template to improve clarity in cases such as this.

**Comment by NielsPilgaard** [comment]
Oh, thank you!

> Perhaps I should add an 'expected behavior' section to the bug report template to improve clarity in cases such as this

That could work 👍
