### ISSUE TITLE
Connection Lost: Network Protocol Issue

### ISSUE THREAD

**Issue by Treeways** [TerminalMC/ClientSort#4]
### Mod Version

v0.4.0-Fabric-1.21 (happens on earlier versions)

### Mod Loader

Fabric

### Minecraft Version

1.21

### Bug Description

When joining a Fabric server, I get the error "Connection Lost: Network Protocol Issue". Only serverside mods are installed on the Fabric server.

Rejoining the server a few times eventually did let me in, but the game stopped loading online player skins.

### Reproduction Steps

1. Install my set of mods.
2. Join any server.

See the log file for my modlist.

### Log File (optional)

https://mclo.gs/HC9WUfu

### Crash Report (optional)

Network Protocol Error Report: https://mclo.gs/mSO7ytb

**Comment by NotRyken** [comment]
This appears to be a conflict with EMI. If you are able to reproduce it without EMI installed on the client, please let me know.
