### ISSUE TITLE
Middle-clicking an item in creative mode sorts the inventory

### ISSUE THREAD

**Issue by Tisawesomeness** [TerminalMC/ClientSort#7]
### Mod Version

0.6.0

### Mod Loader

fabric

### Minecraft Version

1.21

### Bug Description

When middle-clicking an item in creative mode, a stack of 64 items is created as expected, but the inventory is sorted and the items are placed back into the inventory, messing up inventory management. In the original Mouse Wheelie mod, middle-clicking an item in creative mode would not sort the inventory.

### Reproduction Steps

1. Place various items in the creative inventory
2. Middle-click an item
3. Notice that the items are sorted and the new stack of items are placed back into the inventory

**Comment by NotRyken** [comment]
Thanks for reporting. MouseWheelie uses Amecs to handle the keybind, which allows it to avoid this problem, however because ClientSort can't use Amecs I'll have to figure some sort of workaround.
