### ISSUE TITLE
Support for Minecraft 1.20.4 - Neoforge

### ISSUE THREAD

**Issue by greg2126** [TerminalMC/ClientSort#8]
### Request Description

Hey,

Was just wondering if you could add support for minecraft 1.20.4?

Much appreciated.

### Minecraft Version

1.20.4

**Comment by NotRyken** [comment]
That's already covered by [Mouse Wheelie](https://modrinth.com/mod/mouse-wheelie)

**Comment by greg2126** [comment]
Sorry, I forgot to mention if it could be for Neoforge? Mouse wheelie only supports Fabric. Appreciate your time.

**Comment by NotRyken** [comment]
Ah, right. Unfortunately backporting is liable to be a pain with the changes I've made for 1.21. I'll look into it if I get time, but I'm short on that right now so I can't promise anything.
